### ISSUE TITLE
Translate some info to english

### ISSUE THREAD

**Issue by pechinkin** [MatildaZh/TPL13#1]
In //comments and some std::cout text in russian is displayed incorrect. example:
https://github.com/MatildaZh/TPL13/blob/815af8a57bc21c17a751bacbc357fce139f56c20/TPL13/Factory.h#L14
Translating to english will fix this problem

**Comment by ghost** [comment]
Please, change it!!

https://github.com/MatildaZh/TPL13/blob/815af8a57bc21c17a751bacbc357fce139f56c20/TPL13/TPL13.cpp#L57

**Comment by dzhovsdelkunevhodil** [comment]
The English translation is ready.....And  I changed a certain exception
